server:
  port: 1998
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie